Repository ARF-SS13/coyote-bayou, pull requests merged in 2022-09, with the labels that each got.

#709 Second Story House
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: Merge Conflict

#769 Adds checks so admins can't print files using adv. proccall
  code/__HELPERS/_string_lists.dm
  code/__HELPERS/files.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/text.dm
  code/__HELPERS/type2type.dm
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/profiler.dm
  code/game/objects/structures/musician.dm
  code/modules/admin/admin_investigate.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/client/preferences.dm
  code/modules/instruments/songs/play_legacy.dm
  code/modules/mapping/map_config.dm
  code/modules/photography/_pictures.dm
Labels: enhancement, high priority

#770 Bear and Greed's ckey locked loadout!
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: enhancement

#772 Lunasloadout2.0
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: enhancement

#774 Fixes Redwater Watcher Spawn
  _maps/map_files/Pahrump-Sunset/RockSprings.dmm
  tgui/public/tgui.bundle.js
Labels: bugfix, mapping

#775 Loadout kit stuff!
  code/modules/fallout/obj/smelling_salts.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: enhancement, removal

#776 Fixes the Combat Carbine sprite and changes the recipe name
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  icons/obj/guns/projectile.dmi
Labels: bugfix

#778 They're out of the loot pile now! (The parts)
  code/_globalvars/lists/maintenance_loot.dm
Labels: enhancement

#779 Cleaning radioactive goo with Abraxo
  code/modules/fallout/obj/crafting.dm
  code/modules/fallout/obj/decals.dm
Labels: enhancement

#786 Ckey loadout kit, and a fix to another!
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: enhancement

#784 Alphabetizes custom loadout stuff
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: enhancement

#787 Removes a rogue different area tile
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: bugfix, mapping
