Repository ARF-SS13/coyote-bayou, pull requests merged in 2022-07, with the labels that each got.

#129 Subtle(r) changes
  code/__DEFINES/span.dm
  code/datums/emotes.dm
  code/modules/mob/say_vr.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: stale

#357 Enables border control
  config/config.txt
Labels: high priority

#354 Fixed matrix tiles turning permanently green once they've been used
  code/modules/fallout/turf/walls.dm
  tgui/.gitignore
Labels: bugfix

#356 Update compile_changelogs.yml
  .github/workflows/compile_changelogs.yml
Labels: high priority

#406 Adds a fucking deer tail
  modular_coyote/code/mam_tails_coyote.dm
  modular_coyote/icons/mob/mam_tails.dmi
Labels: high priority

#407 Wren sprites added! + Two big fixes
  code/game/objects/structures/beds_chairs/bed.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/fallout/obj/structures/wasteplants.dm
  code/modules/fallout/obj/structures/well.dm
  code/modules/jobs/loadout_ingame.dm
  fortune13.dme
  icons/fallout/objects/decals.dmi
  icons/fallout/turfs/sidewalk.dmi
  icons/obj/Ritas.dmi
  icons/obj/contraband.dmi
  icons/obj/flora/deadtrees.dmi
  icons/obj/musician.dmi
  icons/obj/objects.dmi
  icons/obj/objects2.dmi
  icons/turf/pool.dmi
  modular_coyote/code/modules/hair_gradient/hair_gradient.dm
  modular_coyote/code/modules/mapping/wren_billboards.dm
  modular_coyote/code/modules/say/soundbubbles.dm
Labels: high priority

#438 Lagfix
  .gitignore
  code/modules/jobs/loadout_ingame.dm
  tgui/packages/tgui/interfaces/LoadoutSelect.js
Labels: high priority

#459 FoA Hospital fixes
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: mapping

#463 Fixes some stinky runtimes >:(
  code/__DEFINES/footsteps.dm
  code/controllers/subsystem/mob_spawners.dm
  code/game/objects/items/prize_loot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/research/techweb/nodes/engineering_nodes.dm
Labels: bugfix
