Repository ARF-SS13/coyote-bayou, pull requests merged in 2022-12, with the labels that each got.

#1191 Loadout selector boxes
  code/game/objects/items/loadout_beacons.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/followers.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/jobs/job_types/tribals.dm
  code/modules/jobs/job_types/wasteland.dm
  fortune13.dme
Labels: Merge Conflict

#1340 Gardenbelt fix
  code/game/objects/items/storage/belt.dm
Labels: bugfix

#1338 Pre-war Imitation foods
  code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
Labels: enhancement

#1339 Reskins spade and adds sprite.
  farming_tools.dmi
Labels: Sprites

#1334 Tribal guns, access and crafting.
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: enhancement

#1329 Various gun changes
  code/__DEFINES/ammo.dm
  code/__DEFINES/combat.dm
  code/__DEFINES/wounds.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/loadout_beacons.dm
  code/game/objects/items/storage/belt.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/ammunition/ballistic/sniper.dm
  code/modules/projectiles/ammunition/caseless/ballistic.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/boxes_magazines/internal/_cylinder.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
  code/modules/research/designs/ammolathe_designs.dm
  modular_coyote/eris/code/gun_firemode.dm
Labels: enhancement
