Repository ARF-SS13/coyote-bayou, pull requests merged in 2022-08, with the labels that each got.

#491 New bar and trader
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: mapping

#493 Re-adds the changelog button
  interface/skin.dmf
Labels: enhancement

#495 Re-adding the FoA OR table
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: mapping

#492 Adds linebreaks to *me
  code/modules/mob/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/say.dm
Labels: enhancement

#500 Legion bandanas renamed and put into loadout
  code/modules/clothing/masks/miscellaneous.dm
  modular_citadel/code/modules/client/loadout/mask.dm
Labels: enhancement

#501 Delet Clenbutt
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Labels: mapping

#506 Update game_options.txt & more
  code/modules/arousal/genitals_sprite_accessories.dm
  code/modules/arousal/organs/testicles.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  config/game_options.txt
Labels: enhancement, bugfix

#504 Adds backpack to the backpack section
  code/_globalvars/lists/flavor_misc.dm
  modular_citadel/code/modules/client/loadout/hands.dm
Labels: enhancement

#503 moves outlaw back under 'redwater'
  code/modules/jobs/jobs.dm
Labels: enhancement

#502 *me gets multiline support that doesnt ruin everything
  code/modules/mob/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/say.dm
Labels: enhancement

#517 Update tools.dmi
  icons/fallout/objects/tools.dmi
Labels: bugfix

#518 Oli fixes the north bunker a tad, adds colormate to nash & redwater
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  _maps/map_files/Pahrump-Sunset/RedRiver.dmm
  _maps/map_files/Pahrump-Sunset/RockSprings.dmm
Labels: mapping

#512 adds the 'spearfisher'
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/game/objects/items/fishingrod.dm
  code/modules/jobs/job_types/tribals.dm
  icons/obj/fish/fish_items.dmi
Labels: enhancement

#551 M2405 Magnum Revolver Rifle
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/research/designs/ammolathe_designs.dm
  icons/fallout/objects/guns/ammo.dmi
  icons/fallout/objects/guns/long.dmi
  icons/fallout/onmob/weapons/guns_lefthand.dmi
  icons/fallout/onmob/weapons/guns_righthand.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/ammo.dmi
Labels: enhancement

#555 Gun changes, again
  code/__DEFINES/combat.dm
  code/modules/mob/clickdelay.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/bow.dm
  code/modules/projectiles/guns/ballistic/crafting.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/shotgun.dm
Labels: enhancement

#511 Bloodloss and bleeding overhaul
  code/__DEFINES/armor.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/wounds.dm
  code/datums/components/butchering.dm
  code/datums/diseases/advance/symptoms/oxygen.dm
  code/datums/status_effects/debuffs.dm
  code/datums/wounds/_wounds.dm
  code/datums/wounds/bleed.dm
  code/datums/wounds/bones.dm
  code/datums/wounds/burns.dm
  code/datums/wounds/pierce.dm
  code/datums/wounds/slash.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/antagonists/abductor/equipment/glands/heal.dm
  code/modules/antagonists/bloodsucker/bloodsucker_integration.dm
  code/modules/antagonists/bloodsucker/bloodsucker_life.dm
  code/modules/antagonists/bloodsucker/bloodsucker_powers.dm
  code/modules/antagonists/bloodsucker/datum_bloodsucker.dm
  code/modules/antagonists/bloodsucker/items/bloodsucker_stake.dm
  code/modules/antagonists/bloodsucker/objects/bloodsucker_crypt.dm
  code/modules/antagonists/bloodsucker/powers/feed.dm
  code/modules/antagonists/cult/blood_magic.dm
  code/modules/antagonists/cult/cult_structures.dm
  code/modules/antagonists/cult/ritual.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/eldritch_cult/eldritch_magic.dm
  code/modules/antagonists/eldritch_cult/knowledge/flesh_lore.dm
  code/modules/fallout/reagents/alcohol.dm
  code/modules/fallout/reagents/medicines.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/f13/insects.dm
  code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
  code/modules/mob/living/simple_animal/hostile/f13/wolf.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/movespeed/modifiers/mobs.dm
  code/modules/projectiles/projectile.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/research/nanites/nanite_programs/healing.dm
  code/modules/research/xenobiology/crossbreeding/_weapons.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/repair_puncture.dm
  code/modules/unit_tests/medical_wounds.dm
  fortune13.dme
  tgui/public/tgui.bundle.js
Labels: enhancement

#577 hotfix admin OOC shit
  code/modules/client/verbs/ooc.dm
Labels: bugfix

#585 More horns
  modular_coyote/code/mam_horns_coyote.dm
  modular_coyote/icons/mob/mam_ears.dmi
Labels: enhancement

#582 No. More. Mosin.
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
Labels: removal

#580 Buffs heavy rifle ammo and certain carbines
  code/__DEFINES/combat.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: enhancement

#600 RCD removed from autolathes
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
Labels: removal
