Repository ARF-SS13/coyote-bayou, pull requests merged in 2023-08, with the labels that each got.

#2622 artifacts!
  code/__DEFINES/artifacts.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/radiation.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/weather.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/artifacts.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/validball_spawner.dm
  code/datums/components/artifacts.dm
  code/datums/components/decals/blood.dm
  code/datums/helper_datums/teleport.dm
  code/datums/traits/good.dm
  code/datums/wounds/bleed.dm
  code/game/atoms.dm
  code/game/machinery/analogprocesser.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/game/objects/items.dm
  code/game/objects/items/artifact_finder.dm
  code/game/objects/items/artifacts.dm
  code/game/objects/items/devices/portable_chem_blenderbelt.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/_storage.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/WVM/wmv_buyer.dm
  code/modules/detectivework/evidence.dm
  code/modules/food_and_drinks/kitchen_machinery/food_cart.dm
  code/modules/food_and_drinks/kitchen_machinery/microwave.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/movespeed/_movespeed_modifier.dm
  code/modules/movespeed/modifiers/mobs.dm
  code/modules/photography/photos/album.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/vending/_vending.dm
  code/modules/vending/artifact_hunter.dm
  fortune13.dme
  icons/obj/artifacts.dmi
  icons/obj/storage.dmi
  modular_citadel/code/modules/custom_loadout/load_to_mob.dm
  strings/artifact_affixes.json
Labels: =3 TESTMERGE =3

#2749 Capitalism Two, Electric Boogaloo
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/game/objects/items/cards_ids.dm
  code/modules/WVM/wmv_buyer.dm
  code/modules/WVM/wvm.dm
  code/modules/cargo/exports/misc_export.dm
  code/modules/cargo/packs/materials.dm
  code/modules/cargo/packs/misc.dm
  code/modules/cargo/packs/security.dm
Labels: Merge Conflict

#2775 Adds sound to chem dispensers
  code/datums/components/reskin.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  sound/machines/glassclink.ogg
Labels: prototyping, But actually

#2802 Microdosing gives a lesser effect
  code/__DEFINES/mobs.dm
  code/modules/fallout/reagents/drugs.dm
  code/modules/fallout/reagents/juices.dm
  code/modules/fallout/reagents/medicines.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Merge Conflict

#2823 Adds in sound rocks (that are invisible and not rocks)
  code/controllers/subsystem/processing/weather.dm
  code/controllers/subsystem/timer.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/ambient_sounds.dm
  code/datums/looping_sounds/looping_sound.dm
  code/game/objects/effects/sound_emitter.dm
  fortune13.dme
Labels: documentation, prototyping, But actually

#2837 Adds Pig Ear and Tail
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  icons/mob/mam/citadel/mam_ears.dmi
  icons/mob/mam/citadel/mam_tails.dmi
Labels: prototyping, But actually

#2861 Shy Quirk
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/traits/neutral.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: prototyping, But actually

#2888 This guy really knows how to use his tongue!
  code/datums/traits/neutral.dm
  code/modules/language/codespeak.dm
Labels: Merge Conflict
