Repository ARF-SS13/coyote-bayou, pull requests merged in 2023-10, with the labels that each got.

#3226 Maybe performances up spawners
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/processing/mob_spawner.dm
  code/datums/components/spawner.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: =3 TESTMERGE =3

#3251 Much more armors and weapon adjustments
  code/datums/components/reskin.dm
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/cargo/exports/misc_export.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/arfsuits.dm
  code/modules/clothing/under/f13.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  icons/fallout/clothing/armored_light.dmi
  icons/fallout/clothing/helmets.dmi
  icons/fallout/clothing/uniforms.dmi
  icons/fallout/objects/guns/ballistic.dmi
  icons/fallout/onmob/clothes/armor_light.dmi
  icons/fallout/onmob/clothes/helmet.dmi
  icons/fallout/onmob/clothes/uniform.dmi
  icons/fallout/onmob/weapons/guns_lefthand.dmi
  icons/fallout/onmob/weapons/guns_righthand.dmi
  icons/obj/guns/projectile.dmi
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: Merge Conflict

#3271 Fenny, Dan & Andy eat the code like vultures supping on roadkill
  _maps/map_files/Pahrump-Sunset/RedRiver.dmm
  code/datums/components/mood.dm
  code/datums/components/spawner.dm
  code/datums/components/swarming.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
Labels: do not merge, BAD

#3225 Performances UfoPornhud
  code/__DEFINES/mobs.dm
  code/__HELPERS/text.dm
  code/controllers/subsystem/pornhud.dm
  code/datums/dna.dm
  code/datums/hud.dm
  code/modules/arousal/genitals.dm
  code/modules/arousal/organs/belly.dm
  code/modules/arousal/organs/breasts.dm
  code/modules/arousal/organs/butt.dm
  code/modules/arousal/organs/penis.dm
  code/modules/arousal/organs/testicles.dm
  code/modules/arousal/organs/vagina.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/login.dm
  fortune13.dme
Labels: =3 TESTMERGE =3

#3307 Metal Gear Update
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/uniform.dm
Labels: salt pr, Purple Princess Magic

#3256 Fix some runtimes!
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/second_wind.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/components/storage/ui.dm
  code/datums/components/swarming.dm
  code/datums/components/tackle.dm
  code/datums/emotes.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/atoms_movement.dm
  code/game/objects/hand_items.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/suits/arfsuits.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/logout.dm
  code/modules/reagents/chemistry/holder.dm
  config/maps.txt
  modular_coyote/code/modules/say/soundbubbles.dm
Labels: =3 TESTMERGE =3

#3316 Did the thing Fenny wanted!
  code/datums/components/reskin.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: salt pr, Purple Princess Magic

#3266 Some UI sounds
  code/modules/keybindings/keybind/mob.dm
  sound/effects/switchhand.ogg
  sound/effects/uiclick.ogg
Labels: Come back later

#3309 Disabled Decomposing hostile mobs
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: =3 TESTMERGE =3

#3353 fruit ninja update
  code/game/objects/items/loadout_beacons.dm
  code/game/objects/items/melee/energy.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/shoes/f13.dm
  code/modules/clothing/suits/arfsuits.dm
  code/modules/projectiles/guns/ballistic/bow.dm
  code/modules/projectiles/projectile/reusable/arrow.dm
  icons/fallout/clothing/armored_light.dmi
  icons/fallout/onmob/clothes/armor_light.dmi
  modular_citadel/code/modules/client/loadout/head.dm
  modular_citadel/code/modules/client/loadout/shoes.dm
  modular_citadel/code/modules/client/loadout/suit.dm
  modular_coyote/icons/objects/bows.dmi
Labels: Merge Conflict

#3314 Smart inventory slot unsheathing [ready to merge]
  code/modules/keybindings/keybind/human.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/projectiles/gun.dm
Labels: =3 TESTMERGE =3

#3379 fixes a typo for expensive items 100-299 coins
  code/modules/WVM/wmv_buyer.dm
Labels: bugfix

#3376 Attempts to port tgs pr 55563
  code/datums/hud.dm
  code/modules/mob/dead/observer/observer.dm
Labels: enhancement, help wanted, high priority, do not merge

#3306 disables leaving the game!
  code/__HELPERS/icons.dm
  code/controllers/subsystem/mobs.dm
  code/modules/fallout/turf/walls.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: =3 TESTMERGE =3

#3337 Try to un-runtime the runtimes
  code/datums/traits/_quirk.dm
  code/datums/world_topic.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/reagents/chemistry/holder.dm
Labels: =3 TESTMERGE =3

#3413 Ports the last 2/3rd of tg 67273
  code/controllers/subsystem/npcpool.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: =3 TESTMERGE =3

#3432 peanut butter jelly time
  code/game/gamemodes/dynamic/dynamic.dm
Labels: do not merge

#3447 Kelp's TG Blasters (ACTUALLY GOOD TO MERGE THIS TIME I SWEAR)
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/game/objects/items/loadout_beacons.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  icons/fallout/objects/guns/energy.dmi
Labels: Merge Conflict

#3445 Adds a new laser
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
Labels: help wanted

#3465 Revert "removes another source of green ghosts"
  code/_onclick/hud/screen_objects.dm
Labels: Merge Conflict

#3485 fixes active hand bug again sorry
  code/_onclick/hud/screen_objects.dm
Labels: bugfix, READY

#3547 THE ANGER DESTROYER 9000
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  icons/fallout/mobs/humans/fallout_npc.dmi
  icons/fallout/mobs/humans/ghouls.dmi
Labels: =3 TESTMERGE =3

#3536 Geckos continue to be our star mob part 47
  code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: enhancement, high priority, salt pr, prototyping, =3 TESTMERGE =3, lovedan, Big Dans Big Prs

#3532 Ports tg 56780 - Ryll Ryll really IS cool as shit
  code/__HELPERS/AStar.dm
  code/__HELPERS/heap.dm
  code/__HELPERS/path.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/objs.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/integrated_electronics/subtypes/smart.dm
  code/modules/mob/living/simple_animal/bot/bot.dm
  code/modules/mob/living/simple_animal/bot/cleanbot.dm
  code/modules/mob/living/simple_animal/bot/firebot.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/mob/living/simple_animal/bot/medbot.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/parrot.dm
  fortune13.dme
Labels: =3 TESTMERGE =3

#2925 Prototypes some easier to usepersonality trait icon stuff
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/say_vr.dm
Labels: READY, Big Dans Big Prs

#3564 makes guns squish when you manipulate them
  code/modules/projectiles/guns/ballistic.dm
Labels: READY

#3575 NEWBIE OOC & Its Mute
  code/__DEFINES/admin.dm
  code/__DEFINES/preferences.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/newbie.dm
  fortune13.dme
Labels: prototyping, But actually, READY, MUDification

#3597 guns, glorious guns
  code/__DEFINES/ammo.dm
  code/__DEFINES/inventory.dm
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/game/objects/items/loadout_beacons.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/boxes_magazines/external/smg.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/hoboguns.dm
  code/modules/projectiles/projectile/special/bee.dm
  modular_coyote/eris/code/gun_firemode.dm
  modular_coyote/icons/objects/pistols.dmi
Labels: Merge Conflict

#3609 displays DPS alongside the regular damage when examining a weapon's stats
  code/__DEFINES/misc.dm
  code/game/objects/items.dm
  modular_coyote/eris/code/dual_wielding.dm
  modular_coyote/eris/code/wielding.dm
Labels: enhancement, READY

#3616 money dupe fix
  code/modules/WVM/wvm.dm
Labels: bugfix
