Repository ARF-SS13/coyote-bayou, pull requests merged in 2023-12, with the labels that each got.

#3966 Alt Sprite Picker for Creature Species
  code/__DEFINES/combat.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  modular_coyote/code/creature_species.dm
  modular_coyote/icons/mob/pokemon64.dmi
Labels: READY

#3967 quirks get assigned when CtrlShiftClicking an observer
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob_transformation_simple.dm
Labels: READY

#3980 reduces plant count for memory saving
  code/modules/fallout/turf/ground.dm
  modular_coyote/code/modules/turf_changes/PlantGrass.dm
Labels: READY

#3986 Don't leave a hole in the damn floor
  _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
Labels: salt pr

#3987 Transit Z Cleanup
  code/controllers/subsystem/mapping.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/granters.dm
  code/modules/cargo/packs/skillbooks.dm
  code/modules/mapping/space_management/space_transition.dm
  code/modules/projectiles/ammo_casing_gun_sound_properties.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/sniper.dm
  code/modules/projectiles/boxes_magazines/internal/rifle.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/research/designs/ammolathe_designs.dm
  modular_coyote/code/modules/turf_changes/PlantGrass.dm
  sound/f13weapons/antimaterialfire.ogg
  sound/f13weapons/antimaterialreload.ogg
Labels: READY

#3996 Revert some stuff
  code/modules/mapping/space_management/space_transition.dm
  modular_coyote/code/modules/turf_changes/PlantGrass.dm
Labels: love

#4005 that's quite big
  code/__DEFINES/weather.dm
  code/datums/brain_damage/phobia.dm
  code/datums/mood_events/generic_negative_events.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/modules/clothing/shoes/f13.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/typing_indicator.dm
  code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/typing_indicator.dm
  modular_coyote/code/creature_species.dm
  modular_coyote/code/modules/turf_changes/PlantGrass.dm
Labels: READY

#4019 adds a few xenomorph races from tgmc + queen alt sprite
  icons/mob/alienqueen.dmi
  modular_coyote/code/creature_species.dm
  modular_coyote/icons/mob/tgmc/baneling.dmi
  modular_coyote/icons/mob/tgmc/beetle.dmi
  modular_coyote/icons/mob/tgmc/behemoth.dmi
  modular_coyote/icons/mob/tgmc/boiler.dmi
  modular_coyote/icons/mob/tgmc/bull.dmi
  modular_coyote/icons/mob/tgmc/carrier.dmi
  modular_coyote/icons/mob/tgmc/crusher.dmi
  modular_coyote/icons/mob/tgmc/defender.dmi
  modular_coyote/icons/mob/tgmc/defiler.dmi
  modular_coyote/icons/mob/tgmc/drone.dmi
  modular_coyote/icons/mob/tgmc/gorger.dmi
  modular_coyote/icons/mob/tgmc/hivelord.dmi
  modular_coyote/icons/mob/tgmc/hivemind.dmi
  modular_coyote/icons/mob/tgmc/hunter.dmi
  modular_coyote/icons/mob/tgmc/king.dmi
  modular_coyote/icons/mob/tgmc/larva.dmi
  modular_coyote/icons/mob/tgmc/mantis.dmi
  modular_coyote/icons/mob/tgmc/nymph.dmi
  modular_coyote/icons/mob/tgmc/praetorian.dmi
  modular_coyote/icons/mob/tgmc/puppet.dmi
  modular_coyote/icons/mob/tgmc/puppeteer.dmi
  modular_coyote/icons/mob/tgmc/queen.dmi
  modular_coyote/icons/mob/tgmc/ravager.dmi
  modular_coyote/icons/mob/tgmc/runner.dmi
  modular_coyote/icons/mob/tgmc/scorpion.dmi
  modular_coyote/icons/mob/tgmc/sentinel.dmi
  modular_coyote/icons/mob/tgmc/shrike.dmi
  modular_coyote/icons/mob/tgmc/spitter.dmi
  modular_coyote/icons/mob/tgmc/warlock.dmi
  modular_coyote/icons/mob/tgmc/warrior.dmi
  modular_coyote/icons/mob/tgmc/widow.dmi
  modular_coyote/icons/mob/tgmc/wraith.dmi
Labels: READY

#4021 credits tgmc as the icon source explicitly
  modular_coyote/icons/mob/tgmc/CREDIT.txt
Labels: READY

#3997 Only compare against player mobs on their own Z
  code/datums/components/spawner.dm
Labels: =3 TESTMERGE =3

#4023 Adds a carbonation-based life form
  code/__DEFINES/DNA.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/reagents.dm
  code/controllers/subsystem/second_wind.dm
  code/datums/traits/good.dm
  code/modules/fallout/reagents/alcohol.dm
  code/modules/fallout/reagents/drinks.dm
  code/modules/mob/living/carbon/alien/damage_procs.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/surgery/organs/soda_organ.dm
  fortune13.dme
Labels: =3 TESTMERGE =3
