Repository ARF-SS13/coyote-bayou, pull requests merged in 2023-11, with the labels that each got.

#3651 Sunsets Dynamic 2021
  code/game/gamemodes/dynamic/dynamic.dm
Labels: =3 TESTMERGE =3

#3660 Gun Loot Balancing
  _maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/hoboguns.dm
Labels: Merge Conflict

#3661 re-enables icon2html and more
  code/controllers/subsystem/mobs.dm
  code/modules/client/preferences.dm
  icons/fallout/mobs/animals/dogs.dmi
  icons/fallout/mobs/animals/gecktribe.dmi
  icons/fallout/mobs/animals/wasteanimals.dmi
  modular_coyote/code/_pmon_defines.dm
  modular_coyote/code/mob.dm
Labels: READY

#3656 Attempts to increase the QOL of our new who a bit
  code/__HELPERS/_lists.dm
  code/__HELPERS/cmp.dm
  code/controllers/subsystem/who.dm
Labels: enhancement, help wanted

#3647 Just a rogue thought, don't mind this pr. Probably not important.
  code/controllers/subsystem/garbage.dm
  code/game/objects/items.dm
  modular_coyote/eris/code/mods/_upgrades.dm
  modular_coyote/eris/code/mods/mod_types.dm
Labels: =3 TESTMERGE =3

#3677 Ashdown Clinic
  _maps/map_files/coyote_bayou/Ashdown-Upper.dmm
  _maps/map_files/coyote_bayou/Ashdown.dmm
Labels: enhancement, do not merge, salt pr, Purple Princess Magic, But actually, BAD

#3678 Adjusts the Runechat timers/size and adds Bottom Text :tm:
  code/datums/chatmessage.dm
Labels: enhancement

#3673 resolves two runtimes: looping sounds and projectiles
  code/datums/looping_sounds/_looping_sound.dm
  code/modules/projectiles/projectile.dm
Labels: love

#3685 sprinting bugfix
  code/modules/mob/living/carbon/carbon_sprint.dm
Labels: READY

#3686 phobia and brain tumor balance pass
  code/datums/mood_events/generic_negative_events.dm
  code/datums/traits/negative.dm
Labels: READY

#3702 updates our icon2html to mostly parity with tgstation
  code/__DEFINES/_flags/_flags.dm
  code/__HELPERS/icons.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
Labels: READY

#3735 (MERGE WHEN READY) Lootpool adjustment + massive buffs
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/game/objects/items/loadout_beacons.dm
  code/modules/projectiles/boxes_magazines/internal/shotgun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  icons/fallout/objects/guns/ballistic.dmi
Labels: Merge Conflict

#3752 disables cargo errors
  code/__DEFINES/misc.dm
Labels: READY

#3768 loot and trash piles update
  code/__HELPERS/game.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/modules/fallout/obj/trash_stack.dm
  sound/f13effects/loot_trash.ogg
Labels: READY

#3777 lets you spraypaint any floor
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/crayons.dm
Labels: READY

#3780 creature special and quirk examine
  code/datums/traits/neutral.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/modules/client/preferences.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/fallout/obj/rockitlauncher.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/guns/ballistic/flamethrower.dm
  code/modules/projectiles/guns/ballistic/minigun.dm
  code/modules/projectiles/guns/energy/laser.dm
  modular_coyote/code/pmon_mob.dm
Labels: READY

#3781 fixes missing ID card from loadout
  modular_citadel/code/modules/client/loadout/backpack.dm
Labels: READY

#3802 Adds waddling settings to character creation
  code/__DEFINES/mobs.dm
  code/datums/components/waddling.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: READY

#3804 jungle tree color randomizer
  code/__HELPERS/text.dm
  code/game/objects/structures/flora.dm
Labels: READY

#3807 gas station tune up
  _maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
Labels: READY

#3812 Fixes all of the bugs with butchering
  code/datums/components/butchering.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/hostile/animalhostile.dm
  code/modules/mob/living/simple_animal/hostile/f13/geckotribe.dm
  code/modules/mob/living/simple_animal/hostile/f13/insects.dm
  code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/polarbear.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/wolf.dm
  modular_coyote/code/mob.dm
Labels: READY

#3819 Fixes up the tribal camp a bit more. [READY]
  _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
  _maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
  _maps/map_files/coyote_bayou/Texarkana_underground.dmm
Labels: mapping, READY

#3818 Carbon la cratur
  code/__DEFINES/DNA.dm
  code/__DEFINES/mobs.dm
  code/modules/arousal/genitals.dm
  code/modules/client/preferences.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/living_defines.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/parts.dm
  fortune13.dme
  modular_coyote/code/creature_defines.dm
  modular_coyote/code/creature_hud.dm
  modular_coyote/code/creature_procs.dm
  modular_coyote/code/creature_species.dm
  modular_coyote/code/mob.dm
  modular_coyote/code/pmon_mob.dm
Labels: READY

#3834 Enables Dullahan & Podpeople, Adds Slugcats, Fixes Xenomorph Resting Icons
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/furrypeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  modular_coyote/code/creature_species.dm
  modular_coyote/icons/mob/pokemon64.dmi
Labels: READY

#3799 Starting to port splurts examine/throw/pull icons
  code/controllers/subsystem/gunreticle.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_helpers.dm
  icons/mouse_icons/examine.dmi
  icons/mouse_icons/pull.dmi
  icons/mouse_icons/throw.dmi
Labels: help wanted, Crank it up

#3899 Fix bits panel
  code/__DEFINES/citadel_defines.dm
Labels: =3 TESTMERGE =3

#3904 reduces memory usage
  code/controllers/subsystem/recoil.dm
  code/datums/armor.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/buttons.dm
  code/game/objects/effects/decals/cleanable/gibs.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/game/objects/structures.dm
  code/game/objects/structures/flora.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/projectiles/ammunition/ballistic/shotgun.dm
  code/modules/projectiles/gun.dm
  modular_coyote/code/pmon_mob.dm
Labels: READY

#3882 'Fixes' lathes
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/do_after.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystem/recoil.dm
  code/datums/components/material_container.dm
  code/datums/components/storage/concrete/bags.dm
  code/datums/components/storage/storage.dm
  code/datums/materials/basemats.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  modular_sand/code/datums/interactions/_interaction.dm
  sound/effects/metallic_shift.ogg
  sound/effects/metallic_shift_big.ogg
  tgui/packages/tgui/interfaces/Autolathe.js
Labels: =3 TESTMERGE =3

#3912 *shits in ur atmos simulator cutely
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/environmental/LINDA_fire.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/holodeck/area_copy.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/on_move.dm
Labels: salt pr, =3 TESTMERGE =3, Crank it up

#3953 fixes the Show Tip verb
  code/controllers/subsystem/ticker.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: READY

#3852 gun freeze over after this
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/masterlootdrop.dm
  code/game/objects/items/miscellaneous.dm
  code/game/objects/objs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/cargo/exports/misc_export.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/plasma_cit.dm
  code/modules/projectiles/guns/hoboguns.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
Labels: =3 TESTMERGE =3

#3960 adds mappable bounty hunter ticket spawners
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: READY

#3965 Datapal Geiger Counter, CI Movement Bug Fix, Tough Feet Covered in Superglue & Water
  code/__DEFINES/traits.dm
  code/datums/components/combat_mode.dm
  code/datums/looping_sounds/item_sounds.dm
  code/game/objects/hand_items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/geiger_counter.dm
  code/modules/clothing/shoes/f13.dm
Labels: READY
