Repository ARF-SS13/coyote-bayou, pull requests merged in 2023-09, with the labels that each got.

#2928 Climbing Expansion
  code/datums/looping_sounds/item_sounds.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/simulated/walls.dm
  icons/obj/stairs.dmi
  sound/effects/rocks/rocks1_01.ogg
  sound/effects/rocks/rocks1_02.ogg
  sound/effects/rocks/rocks1_03.ogg
  sound/effects/rocks/rocks1_04.ogg
  sound/effects/rocks/rocks1_05.ogg
  sound/effects/rocks/rocks1_06.ogg
  sound/effects/rocks/rocks1_07.ogg
  sound/effects/rocks/rocks1_08.ogg
  sound/effects/rocks/rocks1_09.ogg
  sound/effects/rocks/rocks1_10.ogg
Labels: help wanted

#2980 Turns off Masked Mook
  code/datums/traits/negative.dm
Labels: do not merge, salt pr, Optional PR - Needs more Work, But actually

#2983 Fixes "masked mook" perk
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/datums/traits/negative.dm
Labels: help wanted, question

#2977 Mood sounds
  code/datums/components/mood.dm
  code/datums/traits/negative.dm
Labels: =3 TESTMERGE =3, lovedan

#2997 Eyepatches - Prototype for adding clothing & to the loadout
  code/modules/clothing/glasses/_glasses.dm
  icons/mob/clothing/eyes.dmi
  icons/obj/clothing/glasses.dmi
  modular_citadel/code/modules/client/loadout/glasses.dm
Labels: documentation, prototyping, But actually

#2999 Encheapens sound rocks
  code/controllers/subsystem/processing/weather.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/game/objects/effects/sound_emitter.dm
Labels: =3 TESTMERGE =3

#3132 axes the proton axe
  code/game/objects/items/melee/f13twohanded.dm
Labels: help wanted, lovedan

#3155 (TEST) Removes the NO_DRUGS trait from Berserker and Raging Boar
  code/datums/martial/berserker.dm
  code/datums/martial/raging_boar.dm
Labels: =3 TESTMERGE =3

#3150 Lets players eat mobs, sort of
  code/controllers/subsystem/vore.dm
  code/modules/vore/eating/vore_core.dm
Labels: =3 TESTMERGE =3

#3216 Refactors pornhud - READY
  code/__DEFINES/mobs.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/qdel.dm
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/pornhud.dm
  code/datums/dna.dm
  code/datums/hud.dm
  code/modules/arousal/genitals.dm
  code/modules/arousal/organs/belly.dm
  code/modules/arousal/organs/breasts.dm
  code/modules/arousal/organs/butt.dm
  code/modules/arousal/organs/penis.dm
  code/modules/arousal/organs/testicles.dm
  code/modules/arousal/organs/vagina.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  fortune13.dme
Labels: READY

#3148 Revamps the who verb into three verbs ready
  code/__DEFINES/admin.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/span.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/voreconstants.dm
  code/__DEFINES/weather.dm
  code/__HELPERS/areas.dm
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/mobs.dm
  code/controllers/subsystem/who.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/verbs/looc.dm
  code/modules/mob/living/living.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  fortune13.dme
  icons/mob/landmarks.dmi
  modular_coyote/code/modules/verbies/whocares.dm
  tgui/packages/tgui/interfaces/WhoAdminPanel.js
Labels: Merge Conflict, =3 TESTMERGE =3
