Repository ARF-SS13/coyote-bayou, pull requests merged in 2024-03, with the labels that each got.

#4585 Massive Mob Overhaul (goes with #4583)
  code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/f13/insects.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
  code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
  code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/wolf.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
  modular_coyote/code/mob.dm
Labels: READY, Crank it up

#4507 TGUIifies the flirt menu
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/chat.dm
  code/controllers/subsystem/flirt/flirt.dm
  code/controllers/subsystem/flirt/flirts.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/mob.dm
  fortune13.dme
  icons/obj/in_hands.dmi
  modular_sand/code/datums/interactions/_interaction.dm
  tgui/packages/tgui/interfaces/FlirtyFlirty.js
  tgui/packages/tgui/interfaces/MobInteraction.js
  tgui/public/tgui.bundle.js
Labels: Merge Conflict

#4681 makes humans and monkeys take damage while on fire
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/life.dm
Labels: READY

#4703 potentially fixes massive client lag
  code/__DEFINES/mobs.dm
  code/datums/wounds/bleed.dm
  code/modules/mining/machine_vending.dm
  modular_splurt/code/modules/research/xenoarch/artifact_list.dm
  modular_splurt/code/modules/research/xenoarch/strange_rock.dm
Labels: =3 TESTMERGE =3
