Repository ARF-SS13/coyote-bayou, pull requests merged in 2024-04, with the labels that each got.

#4797 Update emote.dm
  code/modules/mob/living/carbon/emote.dm
Labels: READY

#4798 removes black outlines on pmon sprites
  modular_coyote/icons/mob/pmon/pikachu.dmi
  modular_coyote/icons/mob/pmon/raichu.dmi
  modular_coyote/icons/mob/pmon/salazzle.dmi
  modular_coyote/icons/mob/pokemon64.dmi
  modular_coyote/icons/mob/pokemon96.dmi
Labels: READY

#4909 fixes weather (again)
  code/__DEFINES/weather.dm
  code/datums/weather/weather.dm
  code/modules/fallout/areas/area.dm
Labels: bugfix

#4924 fixes broken streets having a missing icon state
  code/game/turfs/simulated/floor/f13_floors.dm
Labels: READY

#4964 attack hotkeys
  code/datums/components/melee_special.dm
  code/modules/keybindings/keybind/combat.dm
  code/modules/mob/clickdelay.dm
  code/modules/projectiles/ammunition/_firing.dm
  config/maps.txt
Labels: =3 TESTMERGE =3

#4720 Extends linting functionality
  code/controllers/subsystem/autotransfer.dm
Labels: stale, =3 TESTMERGE =3

#5082 Darker gameplay testmerge
  _maps/map_files/CB-WIP/Eastlands.dmm
  code/controllers/subsystem/nightcycle.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: =3 TESTMERGE =3
