Repository ARF-SS13/coyote-bayou, pull requests merged in 2024-05, with the labels that each got.

#5113 Adjusts Mob Nest Frequency
  code/modules/fallout/turf/ground.dm
  code/modules/mob/living/simple_animal/friendly/pet.dm
  modular_coyote/code/modules/turf_changes/PlantGrass.dm
Labels: READY

#5122 fenny's super tedious project
  code/__DEFINES/loadout.dm
  code/modules/client/preferences.dm
Labels: Merge Conflict

#5127 Reload Gun Hotkey
  code/_onclick/hud/screen_objects/character_actions.dm
  code/modules/keybindings/keybind/combat.dm
  code/modules/mob/inventory.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
Labels: READY

#5115 Experimental sweeping changes to sound
  code/game/sound.dm
Labels: wontfix, =3 TESTMERGE =3

#5146 New Boston Ruins Overhaul
  _maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
  _maps/map_files/coyote_bayou/Newboston-Upper.dmm
  _maps/map_files/coyote_bayou/Newboston.dmm
  code/modules/fallout/turf/ground.dm
  modular_coyote/code/modules/turf_changes/PlantGrass.dm
Labels: =3 TESTMERGE =3

#5162 fixes invisible butter bears
  code/modules/mob/living/simple_animal/hostile/bear.dm
Labels: READY

#5175 Wrench Healing Improvements
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: READY

#5189 fixes strong spiders permakilling people with broken overdose code
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: READY

#5207 Crit mouthfeel tweaks
  _maps/map_files/coyote_bayou/Newboston.dmm
  code/__DEFINES/combat.dm
  code/__DEFINES/mobs.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/recoil.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/extinguisher.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/keybind/carbon.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_mobility.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_mobility.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/flintlock.dm
  code/modules/projectiles/multichance_projectile_hit_behaviour.dm
  code/modules/projectiles/projectile/bullets/special.dm
  code/modules/tgui/states/conscious.dm
  code/modules/tgui/states/not_incapacitated.dm
  icons/mob/screen_gen.dmi
  tgui/packages/tgui/interfaces/WeaponInfo.js
Labels: =3 TESTMERGE =3
