Repository ARF-SS13/coyote-bayou, pull requests merged in 2024-10, with the labels that each got.

#5433 Roguetown Trees (soon :tm:)
  AAADevTool/AAA_DEVELOPMENT_CONFIG.json
  _maps/map_files/coyote_bayou/Newboston.dmm
  code/game/objects/structures/flora.dm
  code/modules/fallout/turf/ground.dm
  fortune13.dme
  modular_roguetown/todo/trees/newtree.dm
  modular_roguetown/todo/trees/tree.dmi
  modular_roguetown/todo/trees/treestuff.dm
Labels: lovedan, Big Dans Big Prs, Crank it up

#5461 Domeification 2
  _maps/map_files/coyote_bayou/Newboston-Upper.dmm
  _maps/map_files/coyote_bayou/Newboston.dmm
  code/game/objects/items/COOLBOOK.dm
  code/game/objects/structures/window.dm
Labels: Merge Conflict

#5526 feat: Minimal ver 2
  code/_onclick/hud/hud.dm
  icons/mob/screen_minimal2.dmi
Labels: enhancement, Sprites, READY
