Repository ARF-SS13/coyote-bayou, pull requests merged in 2024-02, with the labels that each got.

#4431 Stuff no one cares about Pt. 3
  _maps/map_files/coyote_bayou/Newboston-Upper.dmm
  _maps/map_files/coyote_bayou/Newboston.dmm
  code/game/objects/structures/fluff.dm
  code/modules/fallout/areas/area.dm
  icons/obj/stationobjs.dmi
  icons/turf/areas.dmi
Labels: Merge Conflict

#4437 Revert "Revert "Ports Xenoarch from Splurt""
  _maps/map_files/coyote_bayou/Newboston-Upper.dmm
  _maps/map_files/coyote_bayou/Newboston.dmm
  code/game/objects/items/loadout_toolkits.dm
  code/game/turfs/simulated/minerals.dm
  fortune13.dme
  modular_splurt/code/modules/research/xenoarch/artifact.dm
  modular_splurt/code/modules/research/xenoarch/artifact_list.dm
  modular_splurt/code/modules/research/xenoarch/fossil_and_artifact.dmi
  modular_splurt/code/modules/research/xenoarch/strange_rock.dm
  modular_splurt/code/modules/research/xenoarch/tools.dm
  modular_splurt/code/modules/research/xenoarch/tools.dmi
Labels: do not merge

#4438 Revert "Revert "Strangerock = Research""
  code/controllers/subsystem/research.dm
Labels: do not merge

#4518 custom blood color
  code/__HELPERS/mobs.dm
  code/game/atoms.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/blood.dm
Labels: =3 TESTMERGE =3
